### ISSUE TITLE
Allow customising the host startup script

### ISSUE THREAD

**Issue by jonc125** [UCL-CloudLabs/user-portal#14]
As an alternative option to pressing the 'add' submit button, have a 'customise startup script' button that takes you to a separate form where you can edit the default script in a TextArea field. Then deploy from that stage.

**Comment by jonc125** [comment]
As mentioned this morning to clarify the task: I'd rather not have this added as an extra field to the existing form, as then every user needs to fill it in. Rather, I'd like a second submit-type button on the initial form, labelled 'Customise setup script', with hover text explaining what it does ('Select this if you wish to modify the default script run to initialise the new host. The default assumes your git repository contains a Dockerfile describing one service exposed on the given port.')

This will require:
- [x] a new form to be added in `forms/customise_setup.py` with just the setup script TextArea, and a hidden field containing the host id.
- [x] the TextArea should be populated with the default setup script, as created by my `Host.default_setup_script` method.
- [x] a new view (and template) handling display & post of this form. On post it should update the setup_script in the DB (not create a new host) and call the `deploy()` method.
- [x] extra logic in `views_host.py:add()` which checks which submit button was selected, and either deploys directly with the default form, or just saves the data as a new Host in the DB and redirects to the new form.

**Comment by ksrk** [comment]
Hi John,
    We may submit form directly after updating the setup script instead of saving/adding. Our form validation is not happy about this.

**Comment by raquelalegre** [comment]
It needs to take into account users adding single or double quotes to the provisioning script. For example:

echo "Deployment done!"

Also when parsing the terraform provisioning script comas in the inline list don't look quite right. @ksrk thinks this is due to the form returning a `\n` at the beginning of the script content.

**Comment by raquelalegre** [comment]
Also we need to add a test for this specific case.

**Comment by raquelalegre** [comment]
Would also be nice to validate the bash script given by the user instead of waiting until it's run and check it failed 5 minutes later.

**Comment by raquelalegre** [comment]
Done support to ignore blank lines which were making Terraform upset and escaping quotes when user adds them in their script.
