### ISSUE TITLE
Handle failed deployments

### ISSUE THREAD

**Issue by jonc125** [UCL-CloudLabs/user-portal#15]
Consider whether to
- have a 'Failed' status but still list on the dashboard
- automatically remove hosts that don't deploy (but then they can't see errors, so that isn't great)

With the former, we probably need a way for them to edit & retry deploying.
(This will be true generally of the 'edit host' feature, c.f. #26)

**Comment by jonc125** [comment]
See also https://github.com/UCL-CloudLabs/deployer/issues/3, https://github.com/UCL-CloudLabs/deployer/issues/5.

**Comment by ageorgou** [comment]
Done, pending the edit-and-retry (covered in #26).
