### ISSUE TITLE
Add new host form is not working for password

### ISSUE THREAD

**Issue by ksrk** [UCL-CloudLabs/user-portal#24]
- [ ] support password for new hosting

**Comment by jonc125** [comment]
Could you expand on this? What is failing to work? Details are helpful in bug reports!

**Comment by jonc125** [comment]
Sounds like it's because there isn't an SSH key defined so that field is blank in terraform.tf, and Terraform complains. Fix should probably be related to setting an SSH key pair just for use by the portal.

**Comment by jonc125** [comment]
I think this should now be working in the latest branches, but need to check.
