### ISSUE TITLE
Design a database structure for the front-end

### ISSUE THREAD

**Issue by jonc125** [UCL-CloudLabs/user-portal#5]
Needs to have tables at least for:
* Users: UID (pk), UPI (maybe - we can get that from the session), ...
* SSH keys: id (pk), user (fk), public_key, label
* Virtual hosts: id (pk), user (fk), name (unique per user), DNS name (unique), description (may make name redundant?), ...
    * username & password, or SSH key (fk) - for logging in to the machine
    * Terraform state file (JSON) - canonical source of config details, can be refreshed by backend API call

Since hosts can be set up in different ways, we may need some other tables for their config, e.g. a table for Dockerfiles. User needs to fill in for initial creation:
* VM size, base OS, etc from available options (initially fixed)
* Script (sequence of shell commands) to run on the VM (as root?) to set it up
* Port to connect to for testing the service is up & working, and to include in the link to their new website

Maybe another table for user-GitHub repo links? Possibly using python-social-auth here like Dashboard does? Not needed for initial demo, but will be to support private repos #6.

Initial idea was that front-end will query back-end web service to determine machine status when showing the dashboard - this doesn't need to be in the DB. It'll pass a list of unique machine IDs (DNS name?) and get back statuses, including 'this machine has been deleted via the Azure portal' telling it to drop the machine from the DB (or possibly not, in case user wants to recreate it easily?). This may now be done better by refreshing the Terraform state file.

**Comment by jonc125** [comment]
@raquel-ucl, is the Azure child subscription ID going to be per-user or per-host? We'll presumably need to store those in our DB.

**Comment by raquelalegre** [comment]
One user should have one child subscription ID. That subscription ID can have 0..* hosts. This information is discoverable from the Azure Python SDK, but I don't think it's available on Terraform state.

**Comment by jonc125** [comment]
Actually, we do want to store some user info locally, to support an admin view listing all users down the line.

**Comment by jonc125** [comment]
- [ ] TODO: consider whether we can validate allowed DNS name characters in the DB

**Comment by jonc125** [comment]
Postgres has a JSONB type that decomposes JSON data within the DB and lets you pull out parts of a JSON in an SQL query. That may be useful for the Terraform state, but possibly at a later stage - storing JSON as text and parsing within the Flask app is probably fine for now.

**Comment by jonc125** [comment]
I think it might be easiest to keep a `Host` table in the front-end's DB, even if the back-end is separate and has its own. One use case is to support multi-stage configuration of hosts. For instance, if a user wants to customise their VM install script, that will have to go on a second page, which means we need to remember what they put in the first page, either as lots of hidden fields in the second form, or in a DB.

This would also make displaying the dashboard more responsive - the initial page load could return the cached status in the DB, then async JS calls could update it.

The JS would need to call a public API, which we might want to have as part of the front-end rather than exposing the whole back-end? (We also can't do AJAX requests to another domain without using [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)...)
