### ISSUE TITLE
Highlight data compliance issues

### ISSUE THREAD

**Issue by ageorgou** [UCL-CloudLabs/user-portal#59]
Some things to be shown to users to make sure they understand whether or not they should use CloudLabs:

- [ ] Have a note about what kind of data is acceptable. For example, mention that patient data should reside in the UCL Data Safe Haven instead.

- [ ] As part of the host creation form, show some questions related to data sensitivity (based on the classification survey that ISG uses). If the results indicate that the data is not suitable (e.g. scores too highly on sensitivity or other aspects), don't allow the creation to go ahead.

**Comment by raquelalegre** [comment]
We have agreed with ISG we are just doing something similar to what's done in RDS:

https://utilities.rd.ucl.ac.uk/register

The points above are nice to have, but not mandatory and they shouldn't not stop users from creating new VMs.

**Comment by ageorgou** [comment]
Closed by #76.
