### ISSUE TITLE
Set up SSH access to repositories on staging server

### ISSUE THREAD

**Issue by ageorgou** [UCL-CloudLabs/user-portal#69]
I was unable to pull from/push to either this or the admin repository (SSH key authentication failure). I added another remote with password authentication to work around it.

In hindsight, logging in with SSH agent forwarding seems to work, but we should check that we're fine with this, or at least clean up the remote!

**Comment by raquelalegre** [comment]
I use SSH agent forwarding, so I'm happy with that.

**Comment by ageorgou** [comment]
Removed the HTTPS remote and cleaned up references. Closing.
